# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6eb2b1f68c6d0c8c30c164666a1401b345ebe268dac9c20873cf4dc58c30bdf7f52ba05376c223800e1aaa698a281f25dca013100ec12e497d07d1f87166f310

test:
  secret_key_base: 93501b0133c4627c743d3020072beef2645c34d620ae9a838421105ab50f846aceeac55b39c0950b2bea3f4b5e36cd55cbd1c67a72bf9c0e3a0d4d9a897d3f81

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
